<a href="https://colab.research.google.com/github/emredeveloper/Yapay-Zeka-Denemelerim/blob/main/Kernel_Gelu_Cuda_Fast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kernels

In [8]:
import torch
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.pretty import Pretty

from kernels import get_kernel

console = Console()

# 1. Kernel'i indir
activation = get_kernel("kernels-community/activation")

# 2. CUDA'da rastgele tensor
x = torch.randn((10, 10), dtype=torch.float16, device="cuda")

# 3. Aktivasyon için boş tensor
y = torch.empty_like(x)

# 4. Özel GELU çekirdeğini çalıştır
gelu_kernel = activation.gelu_fast(y, x)

# 5. Sonuçları yazdır
console.rule("[bold green]CUDA GELU Aktivasyonu Sonuçları")

console.print(Panel.fit("🔢 [bold yellow]Input Tensor (x)", style="bold"))
console.print(Pretty(x, expand_all=True))

console.print(Panel.fit("🎯 [bold green]Output Tensor (y) after GELU", style="bold green"))
console.print(Pretty(y, expand_all=True))

console.print(Panel.fit("⚙️ [bold cyan]Kernel Function Info", style="bold cyan"))
console.print(gelu_kernel)

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

───────────────────────────────────────── CUDA GELU Aktivasyonu Sonuçları ─────────────────────────────────────────

╭─────────────────────╮
│ 🔢 Input Tensor (x) │
╰─────────────────────╯

tensor([[-0.5859, -0.9023,  0.8687,  1.1562,  1.4082,  0.3303,  3.5781,  0.8242,
          0.0298,  1.3672],
        [-0.1566,  0.6646,  0.7163,  0.0688, -0.2842,  1.3584, -0.3223,  0.3206,
         -0.3364, -1.5488],
        [-0.3877, -0.3218, -0.9424,  0.4407,  0.7949,  1.3535, -1.6982,  0.1317,
         -0.2605,  0.2184],
        [ 0.0305, -0.4026, -1.1367, -1.5732, -1.7803, -1.9326, -0.0952,  0.2007,
          1.8057,  0.7266],
        [-0.1211, -0.2808, -0.0818,  0.9482,  0.1808,  1.2910,  0.4431,  0.3894,
         -0.2686, -1.7041],
        [-1.2021,  1.0752, -0.6333, -2.3672,  0.6587, -0.9062, -1.4893, -0.6006,
          0.8345, -1.3555],
        [ 1.2334,  0.4363, -0.7100,  0.1696,  0.2178,  0.1265,  0.1510, -0.2179,
          2.2676, -0.0097],
        [-0.5249, -2.2070, -1.0400, -0.5142, -1.4756,  0.2695,  0.3662, -0.5884,
          0.2654, -0.6978],
        [-2.2168, -1.7871, -0.8838, -0.4358, -0.2817,  0.1600,  0.7979, -1.0020,
         -0.3005, -0.1201],
        [-1.1523, -0.0897, -0.6445, -2.4648, -0.1272,  0.6421, -1.2373, -1.1318,
          0.9043, -1.5664]], device='cuda:0', dtype=torch.float16)

╭─────────────────────────────────╮
│ 🎯 Output Tensor (y) after GELU │
╰─────────────────────────────────╯

tensor([[-0.1633, -0.1659,  0.7017,  1.0127,  1.2959,  0.2079,  3.5781,  0.6553,
          0.0153,  1.2500],
        [-0.0685,  0.4961,  0.5464,  0.0363, -0.1103,  1.2393, -0.1204,  0.2007,
         -0.1240, -0.0942],
        [-0.1354, -0.1203, -0.1631,  0.2954,  0.6255,  1.2344, -0.0759,  0.0728,
         -0.1035,  0.1281],
        [ 0.0156, -0.1384, -0.1458, -0.0914, -0.0670, -0.0514, -0.0440,  0.1163,
          1.7412,  0.5566],
        [-0.0547, -0.1093, -0.0382,  0.7852,  0.1034,  1.1641,  0.2974,  0.2537,
         -0.1059, -0.0753],
        [-0.1382,  0.9229, -0.1669, -0.0208,  0.4907, -0.1653, -0.1018, -0.1646,
          0.6660, -0.1191],
        [ 1.0986,  0.2917, -0.1697,  0.0962,  0.1276,  0.0696,  0.0846, -0.0901,
          2.2402, -0.0048],
        [-0.1573, -0.0296, -0.1552, -0.1561, -0.1034,  0.1635,  0.2354, -0.1638,
          0.1604, -0.1696],
        [-0.0292, -0.0663, -0.1666, -0.1445, -0.1096,  0.0901,  0.6279, -0.1586,
         -0.1147, -0.0543],
        [-0.1438, -0.0416, -0.1675, -0.0163, -0.0572,  0.4746, -0.1338, -0.1459,
          0.7388, -0.0922]], device='cuda:0', dtype=torch.float16)

╭────────────────────────╮
│ ⚙️ Kernel Function Info │
╰────────────────────────╯

tensor([[-0.1633, -0.1659,  0.7017,  1.0127,  1.2959,  0.2079,  3.5781,  0.6553,
          0.0153,  1.2500],
        [-0.0685,  0.4961,  0.5464,  0.0363, -0.1103,  1.2393, -0.1204,  0.2007,
         -0.1240, -0.0942],
        [-0.1354, -0.1203, -0.1631,  0.2954,  0.6255,  1.2344, -0.0759,  0.0728,
         -0.1035,  0.1281],
        [ 0.0156, -0.1384, -0.1458, -0.0914, -0.0670, -0.0514, -0.0440,  0.1163,
          1.7412,  0.5566],
        [-0.0547, -0.1093, -0.0382,  0.7852,  0.1034,  1.1641,  0.2974,  0.2537,
         -0.1059, -0.0753],
        [-0.1382,  0.9229, -0.1669, -0.0208,  0.4907, -0.1653, -0.1018, -0.1646,
          0.6660, -0.1191],
        [ 1.0986,  0.2917, -0.1697,  0.0962,  0.1276,  0.0696,  0.0846, -0.0901,
          2.2402, -0.0048],
        [-0.1573, -0.0296, -0.1552, -0.1561, -0.1034,  0.1635,  0.2354, -0.1638,
          0.1604, -0.1696],
        [-0.0292, -0.0663, -0.1666, -0.1445, -0.1096,  0.0901,  0.6279, -0.1586,
         -0.1147, -0.0543],
        [-0.1438, -0.0416, -0.1675, -0.0163, -0.0572,  0.4746, -0.1338, -0.1459,
          0.7388, -0.0922]], device='cuda:0', dtype=torch.float16)

In [9]:
import torch
from torchvision import datasets, transforms
from rich.console import Console
from rich.panel import Panel
from rich.pretty import Pretty

from kernels import get_kernel

# Rich terminal nesnesi
console = Console()

# 1. CUDA kernel'i al
activation = get_kernel("kernels-community/activation")

# 2. MNIST veri setinden bir örnek al
transform = transforms.Compose([
    transforms.ToTensor(),                     # [0,1] arası normalizasyon
    transforms.Lambda(lambda x: x.view(-1))    # 28x28'i vektöre çevir (784,)
])
mnist = datasets.MNIST(root="./data", train=False, download=True, transform=transform)
image_tensor, label = mnist[0]  # İlk görüntüyü al
image_tensor = image_tensor.to(dtype=torch.float16, device="cuda")  # CUDA'ya gönder

# 3. GELU aktivasyonu uygula
output_tensor = torch.empty_like(image_tensor)
gelu_kernel = activation.gelu_fast(output_tensor, image_tensor)

# 4. Sonuçları göster
console.rule("[bold green]MNIST Görseli Üzerinde GELU Aktivasyonu")

console.print(Panel.fit("🖼️ [bold yellow]Input Görsel Tensor (x)", style="bold"))
console.print(Pretty(image_tensor, expand_all=False))

console.print(Panel.fit("🎯 [bold green]Output Tensor (y) after GELU", style="bold green"))
console.print(Pretty(output_tensor, expand_all=False))

console.print(Panel.fit("🏷️ [bold cyan]Etiket (Label): " + str(label), style="bold cyan"))
console.print(Panel.fit("⚙️ Kernel: gelu_fast", style="bold magenta"))


Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 9.91M/9.91M [00:00<00:00, 18.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 504kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.56MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 8.83MB/s]


───────────────────────────────────── MNIST Görseli Üzerinde GELU Aktivasyonu ─────────────────────────────────────

╭───────────────────────────╮
│ 🖼️ Input Görsel Tensor (x) │
╰───────────────────────────╯

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.3293, 0.7256, 0.6235, 0.5923, 0.2354,
        0.1412, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8706, 0.9961, 0.9961, 0.9961,
        0.9961, 0.9453, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764,
        0.7764, 0.6665, 0.2040, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2627, 0.4470, 0.2825,
        0.4470, 0.6392, 0.8901, 0.9961, 0.8823, 0.9961, 0.9961, 0.9961, 0.9805,
        0.8979, 0.9961, 0.9961, 0.5488, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0667, 0.2588, 0.0549, 0.2627, 0.2627, 0.2627,
        0.2313, 0.0823, 0.9253, 0.9961, 0.4158, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.3254, 0.9922, 0.8198, 0.0706, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0863, 0.9136, 1.0000, 0.3254, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.5059, 0.9961, 0.9331, 0.1726, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.2313, 0.9766, 0.9961, 0.2432, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.5215, 0.9961, 0.7334, 0.0196, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,


╭─────────────────────────────────╮
│ 🎯 Output Tensor (y) after GELU │
╰─────────────────────────────────╯

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.2072, 0.5557, 0.4573, 0.4282, 0.1396,
        0.0786, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7036, 0.8369, 0.8369, 0.8369,
        0.8369, 0.7822, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064,
        0.6064, 0.4980, 0.1185, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1586, 0.3008, 0.1727,
        0.3008, 0.4719, 0.7241, 0.8369, 0.7158, 0.8369, 0.8369, 0.8369, 0.8203,
        0.7324, 0.8369, 0.8369, 0.3889, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0351, 0.1558, 0.0287, 0.1586, 0.1586, 0.1586,
        0.1368, 0.0439, 0.7607, 0.8369, 0.2749, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.2042, 0.8325, 0.6509, 0.0373, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0461, 0.7485, 0.8408, 0.2042, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.3508, 0.8369, 0.7695, 0.0981, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.1368, 0.8164, 0.8369, 0.1450, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.3643, 0.8369, 0.5635, 0.0100, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,


╭─────────────────────╮
│ 🏷️ Etiket (Label): 7 │
╰─────────────────────╯

╭─────────────────────╮
│ ⚙️ Kernel: gelu_fast │
╰─────────────────────╯