In [3]:
#!pip install kernels

In [2]:
import torch
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.pretty import Pretty

from kernels import get_kernel

console = Console()

# 1. Kernel'i indir
activation = get_kernel("kernels-community/activation")

# 2. CUDA'da rastgele tensor
x = torch.randn((10, 10), dtype=torch.float16, device="cuda")

# 3. Aktivasyon için boş tensor
y = torch.empty_like(x)

# 4. Özel GELU çekirdeğini çalıştır
gelu_kernel = activation.gelu_fast(y, x)

# 5. Sonuçları yazdır
console.rule("[bold green]CUDA GELU Aktivasyonu Sonuçları")

console.print(Panel.fit("🔢 [bold yellow]Input Tensor (x)", style="bold"))
console.print(Pretty(x, expand_all=True))

console.print(Panel.fit("🎯 [bold green]Output Tensor (y) after GELU", style="bold green"))
console.print(Pretty(y, expand_all=True))

console.print(Panel.fit("⚙️ [bold cyan]Kernel Function Info", style="bold cyan"))
console.print(gelu_kernel)

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

layers.py:   0%|          | 0.00/2.02k [00:00<?, ?B/s]

_ops.py:   0%|          | 0.00/233 [00:00<?, ?B/s]

__init__.py:   0%|          | 0.00/1.02k [00:00<?, ?B/s]

_activation_e99cc09_dirty.abi3.so:   0%|          | 0.00/2.50M [00:00<?, ?B/s]

───────────────────────────────────────── CUDA GELU Aktivasyonu Sonuçları ─────────────────────────────────────────

╭─────────────────────╮
│ 🔢 Input Tensor (x) │
╰─────────────────────╯

tensor([[ 0.8765, -0.0593,  1.2051, -0.7544,  1.5273,  0.5044, -0.5508, -0.0630,
          0.7861,  1.0996],
        [ 0.1772, -0.4517, -0.8789, -0.7163,  0.3130,  0.5845,  0.7793, -0.9722,
          0.2659,  0.7539],
        [-1.3750,  1.2246, -0.2825, -0.2859,  0.4634, -0.9648, -0.2329, -0.7290,
          1.1777,  0.0265],
        [ 1.3662,  0.3447,  1.0723, -1.8359,  0.5391, -1.1035, -0.4712, -0.3027,
          0.3486, -0.9927],
        [-0.3767,  0.2145,  0.0967, -0.1896,  1.8926,  0.3577,  1.3525,  0.9775,
          0.5977,  0.0232],
        [-1.1270, -0.1747,  0.1628,  0.0128,  0.4646, -0.3062,  2.1074,  0.6187,
          0.7744,  0.4055],
        [ 1.0430, -0.5767,  0.0489, -1.4717, -1.4014, -0.2383,  0.7021,  0.6973,
         -0.5088, -0.1761],
        [-0.8779, -1.3252,  0.2966,  0.5112, -0.4590, -0.0682, -1.0098, -0.9429,
          2.3281, -0.1642],
        [ 0.2812,  0.9414, -1.6094,  0.3198,  0.2144, -0.1285,  1.7744,  0.4407,
         -0.5947,  0.8198],
        [ 0.9707,  0.0957, -2.1523, -0.0152, -0.4731, -0.1744,  0.5874,  1.3525,
         -0.6328,  0.2729]], device='cuda:0', dtype=torch.float16)

╭─────────────────────────────────╮
│ 🎯 Output Tensor (y) after GELU │
╰─────────────────────────────────╯

tensor([[ 0.7095, -0.0282,  1.0674, -0.1700,  1.4307,  0.3494, -0.1603, -0.0299,
          0.6167,  0.9502],
        [ 0.1011, -0.1471, -0.1670, -0.1698,  0.1949,  0.4211,  0.6094, -0.1609,
          0.1609,  0.5840],
        [-0.1165,  1.0898, -0.1098, -0.1108,  0.3145, -0.1614, -0.0950, -0.1699,
          1.0371,  0.0135],
        [ 1.2490,  0.2189,  0.9204, -0.0610,  0.3801, -0.1489, -0.1503, -0.1154,
          0.2218, -0.1594],
        [-0.1331,  0.1255,  0.0521, -0.0805,  1.8369,  0.2288,  1.2334,  0.8174,
          0.4331,  0.0118],
        [-0.1466, -0.0753,  0.0919,  0.0065,  0.3154, -0.1163,  2.0703,  0.4529,
          0.6045,  0.2666],
        [ 0.8882, -0.1627,  0.0254, -0.1042, -0.1129, -0.0967,  0.5327,  0.5278,
         -0.1555, -0.0757],
        [-0.1670, -0.1229,  0.1830,  0.3555, -0.1483, -0.0322, -0.1577, -0.1630,
          2.3047, -0.0714],
        [ 0.1718,  0.7783, -0.0864,  0.2001,  0.1254, -0.0577,  1.7070,  0.2954,
         -0.1642,  0.6509],
        [ 0.8096,  0.0515, -0.0336, -0.0075, -0.1505, -0.0751,  0.4238,  1.2334,
         -0.1669,  0.1658]], device='cuda:0', dtype=torch.float16)

╭────────────────────────╮
│ ⚙️ Kernel Function Info │
╰────────────────────────╯

tensor([[ 0.7095, -0.0282,  1.0674, -0.1700,  1.4307,  0.3494, -0.1603, -0.0299,
          0.6167,  0.9502],
        [ 0.1011, -0.1471, -0.1670, -0.1698,  0.1949,  0.4211,  0.6094, -0.1609,
          0.1609,  0.5840],
        [-0.1165,  1.0898, -0.1098, -0.1108,  0.3145, -0.1614, -0.0950, -0.1699,
          1.0371,  0.0135],
        [ 1.2490,  0.2189,  0.9204, -0.0610,  0.3801, -0.1489, -0.1503, -0.1154,
          0.2218, -0.1594],
        [-0.1331,  0.1255,  0.0521, -0.0805,  1.8369,  0.2288,  1.2334,  0.8174,
          0.4331,  0.0118],
        [-0.1466, -0.0753,  0.0919,  0.0065,  0.3154, -0.1163,  2.0703,  0.4529,
          0.6045,  0.2666],
        [ 0.8882, -0.1627,  0.0254, -0.1042, -0.1129, -0.0967,  0.5327,  0.5278,
         -0.1555, -0.0757],
        [-0.1670, -0.1229,  0.1830,  0.3555, -0.1483, -0.0322, -0.1577, -0.1630,
          2.3047, -0.0714],
        [ 0.1718,  0.7783, -0.0864,  0.2001,  0.1254, -0.0577,  1.7070,  0.2954,
         -0.1642,  0.6509],
        [ 0.8096,  0.0515, -0.0336, -0.0075, -0.1505, -0.0751,  0.4238,  1.2334,
         -0.1669,  0.1658]], device='cuda:0', dtype=torch.float16)

In [4]:
import torch
from torchvision import datasets, transforms
from rich.console import Console
from rich.panel import Panel
from rich.pretty import Pretty

from kernels import get_kernel

# Rich terminal nesnesi
console = Console()

# 1. CUDA kernel'i al
activation = get_kernel("kernels-community/activation")

# 2. MNIST veri setinden bir örnek al
transform = transforms.Compose([
    transforms.ToTensor(),                     # [0,1] arası normalizasyon
    transforms.Lambda(lambda x: x.view(-1))    # 28x28'i vektöre çevir (784,)
])
mnist = datasets.MNIST(root="./data", train=False, download=True, transform=transform)
image_tensor, label = mnist[0]  # İlk görüntüyü al
image_tensor = image_tensor.to(dtype=torch.float16, device="cuda")  # CUDA'ya gönder

# 3. GELU aktivasyonu uygula
output_tensor = torch.empty_like(image_tensor)
gelu_kernel = activation.gelu_fast(output_tensor, image_tensor)

# 4. Sonuçları göster
console.rule("[bold green]MNIST Görseli Üzerinde GELU Aktivasyonu")

console.print(Panel.fit("🖼️ [bold yellow]Input Görsel Tensor (x)", style="bold"))
console.print(Pretty(image_tensor, expand_all=False))

console.print(Panel.fit("🎯 [bold green]Output Tensor (y) after GELU", style="bold green"))
console.print(Pretty(output_tensor, expand_all=False))

console.print(Panel.fit("🏷️ [bold cyan]Etiket (Label): " + str(label), style="bold cyan"))
console.print(Panel.fit("⚙️ Kernel: gelu_fast", style="bold magenta"))

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 9.91M/9.91M [00:00<00:00, 57.5MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.65MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 15.1MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 8.32MB/s]


───────────────────────────────────── MNIST Görseli Üzerinde GELU Aktivasyonu ─────────────────────────────────────

╭───────────────────────────╮
│ 🖼️ Input Görsel Tensor (x) │
╰───────────────────────────╯

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.3293, 0.7256, 0.6235, 0.5923, 0.2354,
        0.1412, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8706, 0.9961, 0.9961, 0.9961,
        0.9961, 0.9453, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764, 0.7764,
        0.7764, 0.6665, 0.2040, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2627, 0.4470, 0.2825,
        0.4470, 0.6392, 0.8901, 0.9961, 0.8823, 0.9961, 0.9961, 0.9961, 0.9805,
        0.8979, 0.9961, 0.9961, 0.5488, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0667, 0.2588, 0.0549, 0.2627, 0.2627, 0.2627,
        0.2313, 0.0823, 0.9253, 0.9961, 0.4158, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.3254, 0.9922, 0.8198, 0.0706, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0863, 0.9136, 1.0000, 0.3254, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.5059, 0.9961, 0.9331, 0.1726, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.2313, 0.9766, 0.9961, 0.2432, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.5215, 0.9961, 0.7334, 0.0196, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,


╭─────────────────────────────────╮
│ 🎯 Output Tensor (y) after GELU │
╰─────────────────────────────────╯

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.2072, 0.5557, 0.4573, 0.4282, 0.1396,
        0.0786, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7036, 0.8369, 0.8369, 0.8369,
        0.8369, 0.7822, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064, 0.6064,
        0.6064, 0.4980, 0.1185, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1586, 0.3008, 0.1727,
        0.3008, 0.4719, 0.7241, 0.8369, 0.7158, 0.8369, 0.8369, 0.8369, 0.8203,
        0.7324, 0.8369, 0.8369, 0.3889, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0351, 0.1558, 0.0287, 0.1586, 0.1586, 0.1586,
        0.1368, 0.0439, 0.7607, 0.8369, 0.2749, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.2042, 0.8325, 0.6509, 0.0373, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0461, 0.7485, 0.8408, 0.2042, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.3508, 0.8369, 0.7695, 0.0981, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.1368, 0.8164, 0.8369, 0.1450, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.3643, 0.8369, 0.5635, 0.0100, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,


╭─────────────────────╮
│ 🏷️ Etiket (Label): 7 │
╰─────────────────────╯

╭─────────────────────╮
│ ⚙️ Kernel: gelu_fast │
╰─────────────────────╯